In [1]:
import pandas as pd

In [2]:
pd.read_csv('data/IEA Global EV Data 2024.csv')

,region,category,parameter,mode,powertrain,year,unit,value
0,Australia,Historical,EV stock share,Cars,EV,2011,percent,3.900000e-04
1,Australia,Historical,EV sales share,Cars,EV,2011,percent,6.500000e-03
2,Australia,Historical,EV sales,Cars,BEV,2011,Vehicles,4.900000e+01
3,Australia,Historical,EV stock,Cars,BEV,2011,Vehicles,4.900000e+01
4,Australia,Historical,EV stock,Cars,BEV,2012,Vehicles,2.200000e+02
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035,percent,5.500000e+01
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035,percent,3.100000e+01
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035,charging points,9.400000e+06
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035,charging points,1.500000e+07
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035,percent,9.000000e+00

In [3]:
xls = pd.ExcelFile('data/Hydrogen_production_projects_corrected.xlsx')
df1 = pd.read_excel(xls, 'Projects',skiprows=[0,1,2,4,5,6,7,8,9,10])

In [4]:
mobility=df1.loc[df1['EndUse_Mobility'].notnull()]

In [6]:
mobility

,Ref,Project name,Country,Date online,Decomission date,Status,Technology,Technology_details,Technology_electricity,Technology_electricity_details,...,EndUse_CH4 grid inj.,EndUse_CH4 mobility,Announced Size,Capacity_MWel,Capacity_NmÂ³ Hâ‚‚/h,Capacity_kt H2/y,Capacity_t COâ‚‚ captured/y,IEA zero-carbon estimated normalized capacity\n[NmÂ³ Hâ‚‚/hour],References,LOWE_CF
1,3,H2GO Energy Park Oude-Tonge - 1st phase,NLD,2023.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Dedicated renewable,Others/Various,...,NaN,NaN,2.5MW,2.500000,555.555556,0.433133,NaN,555.555556,[503][630][609],0.50
2,4,H2GO Energy Park Oude-Tonge - 2nd phase,NLD,2030.0,NaN,Concept,Other Electrolysis,Unknown PtX,Dedicated renewable,Others/Various,...,NaN,NaN,26MW,23.500000,5222.222222,4.071453,NaN,5222.222222,[503][630][609],0.50
9,11,Green Hysland Mallorca - Phase 1,ESP,2022.0,NaN,Operational,PEM,NaN,Dedicated renewable,Solar PV,...,NaN,NaN,2.5 MW,2.500000,480.769231,0.374827,NaN,480.769231,[317] [319] [594] [682] [691] [692][1239],0.30
10,12,Power to Green H2 Mallorca (GREEN HYSLAND) - P...,ESP,2025.0,NaN,FID/Construction,Other Electrolysis,Unknown PtX,Dedicated renewable,Solar PV,...,NaN,NaN,10,7.500000,1666.666667,1.299400,NaN,1666.666667,[317] [319] [612] [682] [691],0.30
13,16,Fukushima Hydrogen Energy Research Field,JPN,2020.0,2023.0,Operational,ALK,NaN,Dedicated renewable,Solar PV,...,NaN,NaN,10 MW,10.000000,2173.913043,1.694870,NaN,2173.913043,[58] [135] [326] [327] [328],0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1959,2522,Ratcliffe power station - H2 project - phase 1,GBR,2026.0,NaN,Concept,Other Electrolysis,Unknown PtX,Dedicated renewable,Unknown,...,NaN,NaN,100MW,100.000000,22222.222222,17.325333,NaN,22222.222222,[2129],0.50
1960,2523,Ratcliffe power station - H2 project - phase 2,GBR,2030.0,NaN,Concept,Other Electrolysis,Unknown PtX,Dedicated renewable,Unknown,...,NaN,NaN,500MW,400.000000,88888.888889,69.301333,NaN,88888.888889,[2129],0.50
1971,2534,Skipavika Green Ammonia - SkiGA,NOR,2026.0,NaN,Feasibility study,Other Electrolysis,Unknown PtX,Grid+Renewables,Others/Various,...,NaN,NaN,130MW,130.000000,28888.888889,22.522933,NaN,28888.888889,Platts European Gas Daily 29-08-2023,0.70
1981,2544,H2 plant - St Lawrence Hydro Production,USA,2027.0,NaN,Concept,Other Electrolysis,Unknown PtX,Dedicated renewable,Hydropower,...,NaN,NaN,35t H2/day production,92.169944,20482.209738,15.968750,NaN,20482.209738,[2148],0.80
1986,2549,EWE hydrogen plant North Sea coast,DEU,2026.0,NaN,Concept,Other Electrolysis,Unknown PtX,Other/Unknown,Unknown,...,NaN,NaN,320MW,320.000000,71111.111111,55.441067,NaN,71111.111111,[2153],0.57

In [7]:
mobility.to_csv('Mobility_filtered.csv',index=False)